---
title: "Geospatial Data Science Course"
author: "Matt Olson"
date: '2023-11-08'
output: html_document
---
# Special Topics GEOG 490R-001 
### Fall 2023 

> Instructor: Dr. Matt Olson  \
> Email: use Canvas messaging or Matt.Olson@uvu.edu \
> Time: Tues/Thurs 2:30-3:45pm \
> Location: SB 175 (GIS Peper Lab) \
> Office Hours: TBA, Book a time \

## Course Description. 

This course introduces geospatial data science, covering key concepts and techniques for working with geographic data in the R computing environment. Students will learn methods for acquiring, organizing, analyzing, modeling, and visualizing spatial data while gaining hands-on programming experience using R. Real-world examples and spatial data sets will be utilized during assignments and projects. By the end of the course, students will be able to carry out basic geospatial data science workflows in R and apply these skills to relevant problems. 

*This course is equivalent to Geospatial Data Science (GEOG 3440) – which will be offered beginning Spring 2025.*

### Learning Outcomes
By the end of the course, students will be able to: \

* Manage common geospatial data formats alongside proper project organization and version control 
* Apply data wrangling techniques to prepare spatial data for analysis in R 
* Utilize different quantitative methods and geospatial techniques to analyze spatial and non-spatial data 
* Model geographic phenomena and relationships using spatial data science techniques 
* Visualize and communicate geographic information through mapping and graphing methods 
* Create reproducible geospatial data science workflows using R and R Markdown 

### Class Format.  

* Two 75-minute face-to-face class periods per week 
* Class will consist of short lectures, group work, and individual help with tasks 
* Skills acquired throughout the semester will culminate into a final project 

## Resources. 
This course will largely focus on open-source software, texts, and other resources. Which means that everything is free for anyone anywhere to use, if you have access to a computer and the internet. Open-source resources and programs level the playing field and make science and learning more equitable. 

### Course Texts. 
* [Geocomputation with R](https://r.geocompx.org/) by Robin Lovelace, Jakub Nowosad, Jannes Muenchow (ISBN 9781138304512) 
* [R for Data Science](https://r4ds.hadley.nz/) by Hadley Wickam, Mine Cetinkaya-Rundel, and Garret Grolemund 
* Additional readings will be posted  

### Additional resources. 
* Several other online resources can be useful! 

### Software. 
* R and RStudio (Free and open source) 
* R packages including sf, tmap, leaflet, sp, rgdal, raster, terra, etc. * We may dabble in Google Earth Engine 
* Possibly explore geoprocessing with python within QGIS or ArcGISPro (but probably not) 

## Course Structure. 

### Grading. 
* **Tasks:** 30%   
  + Tasks: Assigned near-weekly and will help students build necessary skills throughout the semester 
* **Case Studies:** 25% 
  + Case Studies: Assigned regularly and will challenge students to apply knowledge to solve a real-world geospatial or Earth science problem 
* **Skills Tests:** 15% 
  + Skills tests: Short exams to test your skills in learning the programming language 
* Final Project: 30% 
  + Final Project: The culminating effort of this class will test your ability to apply what you have learned in a class project. The last several weeks of class will focus on preparing students for their project presentation.  

### Class policies. 
* Assignments are due at 11:59 pm on due dates 
* Late work will receive a 6% deduction per day 
* Makeups only given for excused absences with documentation 
* All assignments must be complete and “solved” on your OWN! Learning to problem solve is a key aspect of data science. 
 

### University Policies. 

* AI Statement:Generative AI tools present new ways to brainstorm, fine-tune, and add additional information to your work. These programs are not meant to replace you or your effort when completing a course. Using AI responsibly is import for the modern student and human. Ultimately you are responsible for your assignment submissions in this course and should use personal knowledge, critical thinking, and good judgement with the aid of resources (such as generative AI) to complete assignments. Student work submitting with the help of an AI query should be explicitly stated. No more than 25% of the work can be generated by AI. Plagiarism is no longer limited to the theft of human intellect alone. Reach out if you have any further questions. 

* Academic Integrity: University policies clearly state that plagiarism, cheating, or fabrication will not be tolerated. Give credit where credit is due. Minor violations will result in a failing grade for the assignment and major violations may be reported to the University (possibly resulting in failing the course). For further information, see UVU Policy 541: Student Code of ConductLinks to an external site.. 

* Diversity and Inclusion: “Come as you are. UVU has a place for you.”--President Tuminez. Your experience in this class is important to me and I want you to feel welcome. My goal is to create an inclusive learning atmosphere where students can share, express, and contribute in a safe environment. Please contact me if you have suggestions or concerns. You may also contact the Inclusion and Diversity CommitteeLinks to an external site. to ask for help and support. 

* Food, Housing, Health and Safety: Check out the UVU CARELinks to an external site. page for more resources  

* Additional needs: Students needing accommodations due to a disability including temporary and pregnancy accommodations may contact the UVU Accessibility ServicesLinks to an external site. at accessibilityservices@uvu.edu or 801-863-8747. Accessibility Services is located on the Orem Campus in LC 312.  

### This syllabus and course. 

Syllabus draft and several course ideas were generated in collaboration with Claude natural language AI assistant (Anthropic, Inc., 2023). Other materials may be based on previous online courses and will be indicated in assignments. 

### Course Schedule. 

*not definitive and subject to change*

* Week 1 - Course overview and introduction to geospatial data science, setting up R and spatial packages 
* Week 2 - Introduction to R programming and syntax, working with spatial vector data   
* Week 3 - Tidying, transforming, and exploring spatial data, spatial data visualization 
* Week 4 - Spatial relationships and operations, interactive web mapping * Week 5 - Spatial joins and data aggregation, animated and small multiple maps 
* Week 6 - Choropleth mapping and classification, spatial autocorrelation and clustering  
* Week 7 - Spatial regression modeling, point pattern analysis 
* Week 8 - Interpolation and kriging methods, Midterm Exam 
* Week 9 - Remote sensing data and analysis, creating indices and classifications 
* Week 10 - Environmental modeling applications, spatial optimization techniques 
* Week 11 - Network and transport analysis, shortest paths and service areas 
* Week 12 - Ethics in spatial data science, privacy, surveillance, and bias concerns 
* Week 13 - Student project proposals, reproducible workflows and R Markdown 
* Week 14 - Open lab time for projects, project check-ins and assistance * Week 15 - Student project presentations 

**alternative**

Week	Date	Presentation	Tasks	Case Study	DataCamp
1	8/30/22		Getting Started	Your first script	
2	9/6/22		Graphics Background and Getting started with RStudio	My grandfather says summers are getting hotter	Introduction to R
3	9/13/22		Git Repository	Wealth over time	Introduction to Data Visualization with ggplot
4	9/20/22		Data Wrangling 2	Farthest airport from New York City	Introduction to the Tidyverse
5	9/27/22		Spatial Vector Data	Beware the Canadians!	Communicating with Data in the Tidyverse
6	10/4/22		Spatial Raster Data	Find hottest country on each continent	Visualizing Geospatial Data in R
7	10/11/22		Project Proposal	Getting Help!	Spatial Analysis in R with sf and raster
8	10/18/22		Create Final Project Webpage	One Script, Many Products	Interactive maps with leaflet in R
9	10/25/22		APIs, time-series, and weather Data	Tracking Hurricanes!	Intermediate Data Visualization with ggplot2
10	11/1/22		Remote Sensing	Satellite Remote Sensing	Exploratory Data Analysis in R: Case Study
11	11/8/22		Project First Draft	Parallel Computing with R	
12	11/15/22		Project Peer Review	Dynamic HTML graph of Daily Temperatures	
13	11/22/22		Thanksgiving Week (Tuesday Class Optional)		
14	11/29/22		Project Workshop		
15	12/6/22		Project Workshop	Project Workshop	



*Content is subject to change. Stay tuned for class updates and emails.* 

 