---
title: "Task 8"
author: "GEOG-490R"
date: "Spring 2024"
  html_document:
    code_folding: hide
---

```{r echo=FALSE, message=FALSE}
library(dplyr);library(ggplot2)
```

### Spatial Relationships

Before the break you were introduced to basic spatial data formats. This week we will introduce raster data specifically and explore a few spatial relationships

Intro 

Ideas 

Week 10 - Spatial Analysis I
- Spatial queries & the extract function
- Mapping - arguments
- basic raster?
- Spatial Analysis - Scale and distance
- maybe autocor and interp
  
  + t08
  + cs02?
  + brainstorming project

Week 11???? - maybe remove as not everyone has taken stats - incorporate autocorrelation and interpolation in previous week.
Next week:
- Spatial autocorrelation
- Interpolation
- Spatial distribution models of regression?

Week 11 - Spatial Analysis II
- Raster terrain analysis
- Raster data specifics
  + t09/cs02 - avalanche analysis? or world
  + Project 

Week 12 - Remote Sensing
- Remote Sensing 1
- Remote sensing basics
  + sk02 - spatial data Tues
  + t10

Week 13-15
- More remote sensing examples (students)
  + Project work
  + cs03
  + sk03 (last week)
  + Final Project - Geospatial data science application - Creating a tutorial that explores a uniqe aspect of GDS



\

#### 1. Raster data basics

Geospatial

\

#### 2. Queries, scale, and distance

Geospatial

\

#### 3. More on mapping

Geospatial

\



#### Your Task

Your task this week

\

#### 1. Relationships

Read in...

1. ...






\

#### Submitting

Upload your R Markdown output as an html file to Canvas

\

**This assignment is due in one week but may be turned for an additional week with a late penalty of -5%**

\


