---
title: "Practice"
author: "GEOG-490R"
date: '2024-01-24'
output: html_document
---


Use the `mtcars` dataset to understand basic relationships between variables. 

- The relationship between horsepower and fuel efficiency (mpg). A scatterplot can show if they are linearly related. Is engine power related to gas mileage?

- The distribution of fuel efficiency (mpg). A histogram can show the overall spread and central tendency. How is gas mileage distributed across cars?

- Differences in fuel efficiency by number of cylinders. A grouped boxplot can highlight differences in mpg by the variable cyl. Do cars with more cylinders have lower average mpg?

- The relationship between weight and fuel efficiency. A scatterplot can show if heavier cars tend to have lower mpg. Does weight impact gas mileage?

- Differences in fuel efficiency by transmission type. Group the mpg by am (transmission) and compare with a boxplot or densities plot. Do automatic or manual transmissions have better mpg?

- Horsepower differences by number of cylinders. Use a violin plot or boxplot to compare hp by cyl. Do cars with more cylinders tend to have higher horsepower?

- Weight differences by number of cylinders. Use a grouped boxplot to see how weight varies by cyl. Do cars with more cylinders tend to be heavier?


- Calculate the correlation between mpg and wt. Is this correlation statistically significant at the 0.05 level?

- Using the mtcars data, test whether the average mpg is different between cars with 4, 6, and 8 cylinders using ANOVA

- Write a function that simulates 10 coin flips and returns the number of heads. Run this simulation 1000 times and plot the distribution of heads.

- The relationship between horsepower and fuel efficiency (mpg). A scatterplot can show if they are linearly related. Is engine power related to gas mileage?

- The distribution of fuel efficiency (mpg). A histogram can show the overall spread and central tendency. How is gas mileage distributed across cars?

- Differences in fuel efficiency by number of cylinders. A grouped boxplot can highlight differences in mpg by the variable cyl. Do cars with more cylinders have lower average mpg?

- The relationship between weight and fuel efficiency. A scatterplot can show if heavier cars tend to have lower mpg. Does weight impact gas mileage?

- Differences in fuel efficiency by transmission type. Group the mpg by am (transmission) and compare with a boxplot or densities plot. Do automatic or manual transmissions have better mpg?

- Horsepower differences by number of cylinders. Use a violin plot or boxplot to compare hp by cyl. Do cars with more cylinders tend to have higher horsepower?

- Weight differences by number of cylinders. Use a grouped boxplot to see how weight varies by cyl. Do cars with more cylinders tend to be heavier?